export const buttonList = [
    { name: "AC", className: "button ac-button", id: "clear" },
    { name: "÷", className: "button dark-button", id: "divide" },
    { name: "×", className: "button dark-button", id: "multiply" },
    { name: "7", className: "button light-button", id: "seven" },
    { name: "8", className: "button light-button", id: "eight" },
    { name: "9", className: "button light-button", id: "nine" },
    { name: "-", className: "button dark-button", id: "subtract" },
    { name: "4", className: "button light-button", id: "four" },
    { name: "5", className: "button light-button", id: "five" },
    { name: "6", className: "button light-button", id: "six" },
    { name: "+", className: "button dark-button", id: "add" },
    { name: "1", className: "button light-button", id: "one" },
    { name: "2", className: "button light-button", id: "two" },
    { name: "3", className: "button light-button", id: "three" },
    { name: "=", className: "button dark-button equal-button", id: "equals" },
    { name: "0", className: "button light-button zero-button", id: "zero" },
    { name: ".", className: "button light-button", id: "decimal" },
];
